name: abaadengineering
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  fluttertoast: ^7.1.8
  package_info: ^2.0.0
  http: ^0.13.0
  shared_preferences: ^2.0.4
  path_provider: ^2.0.1
  path: ^1.8.0
  camera: ^0.8.0
  image_picker: ^0.7.3
  mime: ^1.0.0
  file_picker: ^3.0.0
  liquid_progress_indicator: ^0.3.2
  permission_handler: ^6.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.0
  #date_format: ^2.0.4
  #flutter_chat: 2.0.3
  #stream_chat_flutter: 0.2.11
  percent_indicator: "^2.1.7+2"
  syncfusion_flutter_gauges: ^18.2.44
  flutter_phone_direct_caller: ^2.0.0
  open_whatsapp: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  gradient_widgets: ^0.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - images/Icon Set_page_30.png
    - images/logo.svg
    - images/villa_progress1.svg
    - images/villa_location.svg
    - images/uploads_n_documents.svg
    - images/payments_n_collections.svg
    - images/monthly_report.svg
    - images/contact_us.svg
    - images/approved_drawings.svg
    - images/consultant_profile.svg
    - images/profile1.jpg
    - images/profile2.jpg
    - images/profile3.jpg
    - images/profile4.jpg
    - images/home.svg
    - images/account.svg
    - images/cloud.svg
    - images/upload.svg
    - images/download.svg
    - images/camera.svg
    - images/gallery.svg
    - images/img_1.jpg
    - images/img_2.jpg
    - images/img_3.jpg
    - images/img_4.jpg
    - images/img_5.jpg
    - images/img_6.jpg
    - images/img_7.jpg
    - images/img_8.jpg
    - images/img_9.jpg
    - images/img_10.jpg
    - images/img_11.jpg
    - images/img_12.jpg
    - images/img_13.jpg
    - images/img_14.jpg
    - images/img_15.jpg
    - images/img_16.jpg
    - images/img_17.jpg
    - images/img_18.jpg
    - images/img_19.jpg
    - images/img_20.jpg
    - images/img_21.jpg
    - images/img_22.jpg
    - images/img_23.jpg
    - images/img_24.jpg
    - images/img_25.jpg
    - images/img_26.jpg
    - images/img_27.jpg
    - images/img_28.jpg
    - images/img_29.jpg
    - images/img_30.jpg
    - images/img_31.jpg
    - images/img_32.jpg
    - images/img_33.jpg
    - images/img_34.jpg
    - images/img_35.jpg
    - images/img_36.jpg
    - images/img_37.jpg
    - images/img_38.jpg
    - images/img_39.jpg
    - images/img_40.jpg
    - images/img_41.jpg
    - images/img_42.jpg
    - images/img_43.jpg
    - images/img_44.jpg
    - images/icon_jpg.svg
    - images/icon_pdf.svg
    - images/vision.svg
    - images/contact.svg
    - images/design.svg
    - images/feedback.svg
    - images/work.svg
    - images/marker.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
